name: Github Release

on:
  push:
    branches: [main]

jobs:
  unix-builds:
    name: Unix Builds
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        goos:
          [linux, darwin, freebsd, openbsd, netbsd, dragonfly, plan9, solaris]
        goarch: [amd64, arm64]

    steps:
      - name: Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: "^1.21"

      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Git Fetch Tags
        run: git fetch --prune --unshallow --tags -f

      - name: Go Build
        run: CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -trimpath -ldflags="-s -w" -o ./godns_${{ matrix.goos }}-${{ matrix.goarch }} .

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: unix-builds
          path: ./godns_*

  windows-builds:
    name: Windows Builds
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        goos: [windows]
        goarch: [amd64, arm64]

    steps:
      - name: Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: "^1.21"

      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Git Fetch Tags
        run: git fetch --prune --unshallow --tags -f

      - name: Go Build
        run: CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -trimpath -ldflags="-s -w" -o ./godns_${{ matrix.goos }}-${{ matrix.goarch }}.exe .

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: windows-builds
          path: ./godns_*

  tagged-release:
    needs: [unix-builds, windows-builds]

    name: "Tagged Release"
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - run: mkdir -p ./builds
      - uses: actions/download-artifact@v3
        with:
          path: ./builds

      - name: "Publish Release"
        uses: "bishopfox/action-gh-release@v1"
        with:
          files: |
            ./builds/*
